# This file was generated by GoReleaser. DO NOT EDIT.
cask "bronto" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "e1ee8919c9b608e08f2414d45cdfc756334045682209945d666c529b6f2077d7"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "00ee5068b4d913a0a153c671fb5494e191fc1b0b4ee57f5b54680d9be993e52c"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad95744f09cb919fa6cd3280758e94fa9c5b9292093991610e1304b93e0b23a5"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ebde23c2ab2b947472e70e9b5b2971b4fd7d92c7058e4cbd52aede161891cf3"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bronto"
  desc "Community CLI for the Bronto observability platform"
  homepage "https://github.com/bronto-community/bronto-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bronto"
  bash_completion "completions/bronto.bash"
  fish_completion "completions/bronto.fish"
  zsh_completion "completions/bronto.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
