# This file was generated by GoReleaser. DO NOT EDIT.
cask "bronto" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "2958c8846877e147a653fe664cbe124d269af95f56f0065d105c91cbce4dcdca"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "716be0a5162e53d1d3daa85456f91ac9ff03ce81793d4d7903d4d2556b85635f"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c263d18560153dc897ec44315747d7eca322da4b1ebc02ced238e7be269ad137"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "01547751a12a5f9b8d3937bd43bdfe9dea535925150e4c14661e9d8ac4826188"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v#{version}/bronto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bronto"
  desc "Community CLI for the Bronto observability platform"
  homepage "https://github.com/bronto-community/bronto-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bronto"
  bash_completion "completions/bronto.bash"
  fish_completion "completions/bronto.fish"
  zsh_completion "completions/bronto.zsh"

  # No zap stanza required

end
