# This file was generated by GoReleaser. DO NOT EDIT.
cask "bronto" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "30fba9d42b7fe85b33e89d643568d217d059fe3be5a8bb6c01ff77dee18707cd"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v0.2.2/bronto_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "90eabc5313b2c5559de21db454ce843480a931bbeb5a796914095df79d207684"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v0.2.2/bronto_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f68af0f373305b26013db90a55225af54c6bbb89ab3c59d74282e209df0ec7f2"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v0.2.2/bronto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc64261e066cb61f3e625ecda17b64caa5894bfe4f2c8eb7f29037fb31df9706"
      url "https://github.com/bronto-community/bronto-cli/releases/download/v0.2.2/bronto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bronto"
  desc "Community CLI for the Bronto observability platform"
  homepage "https://github.com/bronto-community/bronto-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bronto"
  bash_completion "completions/bronto.bash"
  fish_completion "completions/bronto.fish"
  zsh_completion "completions/bronto.zsh"

  # No zap stanza required
end
