# This file was generated by GoReleaser. DO NOT EDIT.
cask "compy" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "426fc7f3523c580a381e3446b28c84eafe93c93f925133307c55e1b3591cf484"
      url "https://github.com/bronto-community/compy/releases/download/v#{version}/compy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52968ea23ab66f618aafcc32187e328ed4cb9da50e0121a096d35f865db36190"
      url "https://github.com/bronto-community/compy/releases/download/v#{version}/compy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "compy"
  desc "Local OpenTelemetry Collector manager for the dev loop"
  homepage "https://github.com/bronto-community/compy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
    tray_plist = File.expand_path("~/Library/LaunchAgents/io.bronto.compy.tray.plist")
    if File.exist?(tray_plist)
      system_command "/bin/launchctl", args: ["bootout", "gui/#{Process.uid}/io.bronto.compy.tray"], must_succeed: false
      system_command "/bin/launchctl", args: ["bootstrap", "gui/#{Process.uid}", tray_plist], must_succeed: false
    end
  end

  uninstall launchctl: [
      "io.bronto.compy.tray",
      "io.bronto.compy.collector",
    ]

  zap trash: [
      "~/Library/LaunchAgents/io.bronto.compy.tray.plist",
      "~/Library/LaunchAgents/io.bronto.compy.collector.plist",
      "~/Library/Application Support/compy",
    ]

  caveats <<~EOS
    The menu bar icon is opt-in: run `compy tray install`.
  EOS
end
