# This file was generated by GoReleaser. DO NOT EDIT.
cask "compy" do
  depends_on macos: ">= :big_sur"

  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "d294b70915a75e12c5617832d4fbf12f8a00521138bdb480f53ef0dca83ba6d5"
      url "https://github.com/bronto-community/compy/releases/download/v#{version}/compy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d27cc24286f97e4268a03be0d894ef534bc0770ec1f6f10f46e2661eff61ff3"
      url "https://github.com/bronto-community/compy/releases/download/v#{version}/compy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "compy"
  desc "Local OpenTelemetry Collector manager for the dev loop"
  homepage "https://github.com/bronto-community/compy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  uninstall launchctl: [
      "io.bronto.compy.tray",
      "io.bronto.compy.collector",
    ]

  zap trash: [
      "~/Library/LaunchAgents/io.bronto.compy.tray.plist",
      "~/Library/LaunchAgents/io.bronto.compy.collector.plist",
      "~/Library/Application Support/compy",
    ]

  caveats <<~EOS
    compy's menu bar item is opt-in. To add it:

      compy tray install

    It then starts at login. Remove it with "Remove from Menu Bar" in its
    menu, or `compy tray uninstall`.
  EOS
end
