# This file was generated by GoReleaser. DO NOT EDIT.
cask "compy" do
  depends_on macos: ">= :big_sur"

  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "d8e3118f59746cc0043e9c1aef161879aa96864c7f3c84c6b6ed65acacb26cd6"
      url "https://github.com/bronto-community/compy/releases/download/v#{version}/compy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a88dbed96e29b853c3b23318b89f4d45630da5f3ec9ada46e950e9497e9f9b66"
      url "https://github.com/bronto-community/compy/releases/download/v#{version}/compy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "compy"
  desc "Local OpenTelemetry Collector manager for the dev loop"
  homepage "https://github.com/bronto-community/compy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  uninstall launchctl: [
      "io.bronto.compy.tray",
      "io.bronto.compy.collector",
    ]

  zap trash: [
      "~/Library/LaunchAgents/io.bronto.compy.tray.plist",
      "~/Library/LaunchAgents/io.bronto.compy.collector.plist",
      "~/Library/Application Support/compy",
    ]

  caveats <<~EOS
    compy's menu bar item is opt-in. To add it:

      compy tray install

    It then starts at login. Remove it with "Remove from Menu Bar" in its
    menu, or `compy tray uninstall`.
  EOS
end
